import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Script from 'next/script';

export default function Home() {
  return (
    <div className='staticshield-div'>
      <Script
        // src='http://localhost:1337/script.js'
        src='https://staticshield.vercel.app/script.js'
        data-cap='The password is 123test123'
        data-site-id='e1e74f43-888b-42e8-aa6d-9c73bfc74a1b'
        strategy='beforeInteractive'></Script>
      <div className={styles.container}>
        <Head>
          <title>Password protected site</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <noscript>
          <meta
            httpEquiv='refresh'
            content='0; url=https://staticshield.vercel.app/errors/noscript'
          />
        </noscript>
        <main className={styles.main}>
          <h1 className={styles.title}>
            You just visited a password protected site!!
          </h1>

          <div className={styles.grid}>
            <a href='https://nextjs.org/docs' className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>
                Find in-depth information about StaticShield and its features.
              </p>
            </a>

            <a
              href='https://github.com/vercel/next.js/tree/master/examples'
              className={styles.card}>
              <h2>Examples &rarr;</h2>
              <p>
                Discover StaticShield boilerplate projects with various
                frameworks.
              </p>
            </a>
          </div>
        </main>
      </div>
      <style jsx>{`
        .staticshield-div {
          display: none;
        }
      `}</style>
    </div>
  );
}
