import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Script from 'next/script';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Password protected site</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Script
        src='https://staticshield.vercel.app/script.js'
        data-site-id='e1e74f43-888b-42e8-aa6d-9c73bfc74a1b'
        strategy='beforeInteractive'></Script>
      <Head>
        <noscript>
          <meta
            // http-equiv='refresh'
            content='0; url=http://localhost:3000/errors/noscript'
          />
        </noscript>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          You just visited a password protected site!!
        </h1>

        <div className={styles.grid}>
          <a href='https://nextjs.org/docs' className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href='https://nextjs.org/learn' className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}>
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  );
}
